# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ollama-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ollama-app
    spec:
      containers:
      - args:
        - serve
        env:
        - name: FOO
          value: BAR
        image: docker.io/ollama/ollama:latest
        imagePullPolicy: Always
        name: ollama
        ports:
        - containerPort: 11434
          name: frontend
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.ollama
          name: ollama-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
---
# Service ollama
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  selector:
    app: ollama-app
  ports:
    - name: frontend
      protocol: TCP
      port: 11434
      targetPort: frontend
