apiVersion: 1.0.0
metadata:
  generateName: crw_ai_cpu_
projects:
  - name: demo_crw_ai_repo
    source:
      type: git
      location: 'https://github.com/sa-mw-dach/demo_crw_ai.git'
      branch: feature/first_running_version
components:
  - type: cheEditor
    alias: theia-editor
    id: eclipse/che-theia/latest
    memoryLimit: 1Gi
  - type: chePlugin
    id: ms-python/python/latest
    preferences:
      python.globalModuleInstallation: true
  - type: dockerimage
    alias: python
    image: quay.io/eclipse/che-python-3.8:ce0526f
    memoryLimit: 4Gi
    mountSources: true
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: redhat/vscode-xml/latest
    type: chePlugin
commands:
  - name: 01_license_plate__Run server
    actions:
      - type: exec
        component: python
        command: '/bin/bash demos/01_license_plate/run_server.sh'
        workdir: '${CHE_PROJECTS_ROOT}/demo_crw_ai_repo'
  - name: 01_license_plate__Test AI model
    actions:
      - type: exec
        component: python
        command: 'python3 demos/01_license_plate/test_ai_model.py'
        workdir: '${CHE_PROJECTS_ROOT}/demo_crw_ai_repo'
