apiVersion: 1.0.0
metadata:
  generateName: crw_ai_gpu_
projects:
  - name: demo_crw_ai_repo
    source:
      type: git
      location: 'https://github.com/sa-mw-dach/demo_crw_ai.git'
      branch: feature/first_running_version
components:
  - type: cheEditor
    alias: theia-editor
    id: eclipse/che-theia/latest
    memoryLimit: 1Gi
  - type: chePlugin
    id: ms-python/python/latest
    preferences:
      python.globalModuleInstallation: true
  - mountSources: true
    referenceContent: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: python
      spec:
        containers:
          - name: python
            image: quay.io/manhah/ubi8-python3-cuda@sha256:7a72ce783f07887058e27bdb25ee388c34d1629d1312605e1f66068b8da5877c
            resources:
              limits:
                memory: 4Gi
                nvidia.com/gpu: 1 # limiting to 1 GPU
              requests:
                nvidia.com/gpu: 1 # requesting 1 GPU
        nodeSelector:
          nvidia.com/gpu.present: true
    type: kubernetes
    alias: python
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: redhat/vscode-xml/latest
    type: chePlugin
commands:
  - name: 01_license_plate__1 Run server
    actions:
      - type: exec
        component: python
        command: '/bin/bash demos/01_license_plate/run_server.sh'
        workdir: '${CHE_PROJECTS_ROOT}/demo_crw_ai_repo'
  - name: 01_license_plate__2 Test AI model
    actions:
      - type: exec
        component: python
        command: '. ${HOME}/.venv/bin/activate && python demos/01_license_plate/test_ai_model.py'
        workdir: '${CHE_PROJECTS_ROOT}/demo_crw_ai_repo'
  - name: 01_license_plate__3 Test GPU computation
    actions:
      - type: exec
        component: python
        command: '. ${HOME}/.venv/bin/activate && python demos/01_license_plate/test_gpu.py'
        workdir: '${CHE_PROJECTS_ROOT}/demo_crw_ai_repo'
