kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: application
spec:
  to:
    kind: Service
    name: application
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
