apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: licenseplate-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: github-push
      kind: ClusterTriggerBinding
  template:
    ref: licenseplate-template
