FROM registry.access.redhat.com/ubi9/ubi

LABEL description="R-Shiny image based on RHEL UBI9"
LABEL version="1.0"

USER root

RUN dnf update -y
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    /usr/bin/crb enable && \
    dnf install -y epel-release && \
    dnf install -y flexiblas-* && \
    dnf install -y openblas-openmp && \
    dnf install -y flexiblas-openblas-openmp && \
    dnf update -y
RUN dnf install -y pkgconf-pkg-config && \
    dnf install -y flexiblas && \
    dnf install -y libtirpc && \
    dnf install -y perl-libs && \
    dnf install -y perl-Unicode-EastAsianWidth && \
    dnf install -y texinfo && \
    dnf install -y texinfo-tex && \
    dnf install -y flexiblas-netlib64 && \
    dnf install -y flexiblas-devel && \
    dnf install -y libtirpc-devel && \
    dnf update -y && \
    dnf install -y R && \
    dnf install -y libsodium-devel.x86_64 && \
    dnf install -y libgit2-devel.x86_64 && \
    dnf install -y libcurl-devel && \
    dnf install -y cmake
RUN dnf -y install glibc-langpack-en

ENV LANG en_US.UTF-8

RUN R -q -e 'install.packages(c("dplyr", "rpart","utf8", "generics", "bslib", "tibble", "xgboost", "httr", "jsonlite"), repos = "https://cran.rstudio.com/")'

RUN mkdir /application
WORKDIR /application

USER 1001
ENTRYPOINT R -s -e 'library("shiny"); runApp(host = "0.0.0.0", port = 3838)'
