schemaVersion: 2.1.0
metadata:
  name: ai-gpu
components:
  - name: python
    container:
      image: quay.io/manhah/license_plate_demo_gpu:latest
      memoryLimit: 4Gi
      mountSources: true
      sourceMapping: /projects
