schemaVersion: 2.1.0
metadata:
  name: developer-images
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
- name: devtools
  kubernetes:
    inlined:
      apiVersion: v1
      kind: Pod
      metadata:
        name: devtools
      spec:
        containers:
          - name: devtools
            image: nvcr.io/nvidia/driver@sha256:3df118f2330e95db3c76173cca35e542b2da120ec0bb8f6aff83c4c96c0c2daf
