schemaVersion: 2.1.0
metadata:
  name: nvidia-test
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
- name: nvidia-test
  container:
    image: nvcr.io/nvidia/driver@sha256:3df118f2330e95db3c76173cca35e542b2da120ec0bb8f6aff83c4c96c0c2daf
    memoryLimit: 4Gi
    mountSources: false
    sourceMapping: /projects
